[[languages.cpp.environments]]
CXX = 'g++'
CXXFLAGS = [
  '-std=c++17',
  '-O2',
  '-Wall',
  '-Wextra',
  '-Wshadow',
  '-Werror',
  '-Wno-char-subscripts',
  '-Wno-unused-result',
  '-fsanitize=undefined,address',
  '-ftrapv',
]
